USE SistemBeritaAcara;
GO
SET QUOTED_IDENTIFIER ON;

SET IDENTITY_INSERT BACounter ON;
INSERT INTO BACounter (Id, NextValue) SELECT 1, 1 WHERE NOT EXISTS (SELECT 1 FROM BACounter);
SET IDENTITY_INSERT BACounter OFF;
GO
